---

- name: Install kitty Mac
  homebrew_cask:
    name: "kitty"
    state: latest
  when: 
    - ansible_facts['system'] == "Darwin"


- name: Install kitty linux
  shell: curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin launch=n
  args:
    warn: no
  when: 
    - ansible_facts['system'] == "Linux"

- name: Create symlink kitty Linux
  become: yes
  file: src=/home/{{ ansible_user_id }}/.local/kitty.app/bin/kitty dest=/home/{{ ansible_user_id }}/.local/bin/ state=link
  when: 
    - ansible_facts['system'] == "Linux"


- name: Copy kitty Linux Desktop Setup
  copy:
    src: /home/{{ ansible_user_id }}/.local/kitty.app/share/applications/kitty.desktop
    dest: /home/{{ ansible_user_id }}/.local/share/applications
  when: 
    - ansible_facts['system'] == "Linux"

- name: Update kitty Linux Desktop Config
  shell: sed -i "s|Icon=kitty|Icon=/home/$USER/.local/kitty.app/share/icons/hicolor/256x256/apps/kitty.png|g" ~/.local/share/applications/kitty.desktop
  args:
    warn: no
  when: 
    - ansible_facts['system'] == "Linux"