---

- name: Install dep Mac
  homebrew:
    name: "dep"
    state: latest
  when: 
    - ansible_facts['system'] == "Darwin"

- file:
    path: "~{{ username }}/go/bin"
    state: directory
  become: true
  become_method: sudo
  become_user: '{{ username }}'
  
- name: Install dep Linux
  shell: curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  args:
    warn: no
  when: 
    - ansible_facts['system'] == "Linux"
