---
- name: uninstall fprintd
  become: yes
  apt:
    name: fprintd
    state: absent
  when: 
    - ansible_facts['system'] == "Linux"

- apt_repository:
  repo: ppa:uunicorn/open-fprintd
  when: 
    - ansible_facts['system'] == "Linux"

- name: install open-fprintd
  become: yes
  apt:
    name: open-fprintd
    state: present
  when: 
    - ansible_facts['system'] == "Linux"

- name: install fprintd-clients
  become: yes
  apt:
    name: fprintd-clients
    state: present
  when: 
    - ansible_facts['system'] == "Linux"

- name: install python3-validity
  become: yes
  apt:
    name: python3-validity
    state: present
  when: 
    - ansible_facts['system'] == "Linux"
