---
- name: uninstall fprintd
  become: yes
  apt:
    name: fprintd
    state: absent
  when: 
    - ansible_facts['system'] == "Linux"

- name: Install open-fprintd repo
  become: yes
  shell: add-apt-repository ppa:uunicorn/open-fprintd 
  args:
    warn: no
  when: 
    - ansible_facts['system'] == "Linux"

- name: install open-fprintd
  become: yes
  apt:
    name: open-fprintd
    state: present
    update_cache: yes
  when: 
    - ansible_facts['system'] == "Linux"

- name: install fprintd-clients
  become: yes
  apt:
    name: fprintd-clients
    state: present
  when: 
    - ansible_facts['system'] == "Linux"

- name: install python3-validity
  become: yes
  apt:
    name: python3-validity
    state: present
  when: 
    - ansible_facts['system'] == "Linux"
