---
- name: Download and unarchive awscli Linux.
  become: true
  unarchive:
    src: https://awscli.amazonaws.com/awscli-exe-linux-{{ awscli_platform }}-{{ awscli_version }}.zip
    dest: /home/{{ ansible_user_id }}/tmp/aws
    remote_src: true
    creates: "/home/{{ ansible_user_id }}/tmp/aws/install"
    mode: 0755
  when: 
    - ansible_facts['system'] == "Linux"


- name: Install awscli Mac
  homebrew:
    name: "awscli"
    state: latest
  when: 
    - ansible_facts['system'] == "Darwin"


- name: Install awscli version {{ awscli_version }} Linux
  command: /home/{{ ansible_user_id }}/tmp/aws/install
  when: 
    - ansible_facts['system'] == "Linux"

- name: Cleanup awscli tmp folder
  file:
    path: /home/{{ ansible_user_id }}/tmp/aws/
    state: absent
  when: 
    - ansible_facts['system'] == "Linux"