---

- name: Install azure-cli Mac
  homebrew:
    name: "azure-cli"
    state: latest
  when: 
    - ansible_facts['system'] == "Darwin"


- name: Install azure-cli Linux
  shell: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash -
  args:
    warn: no
  when: 
    - ansible_facts['system'] == "Linux"