#- name: Copy Nano Highlights
#  copy:
#    src: .nano/
#    dest: ~/.nano/

#Clone Plugins

- name: clone tmux plugin - {{ plugins.name }}
  ansible.builtin.git:
    repo: https://git::@github.com/{{ plugins.git }}
    dest: ~/.tmux/{{ plugins.folder }}
    clone: yes
    update: yes
  with_items: "{{ plugins | map(attribute='plugins') | list }}"
  loop_control:
    loop_var: plugins
    

- name: Copy tmux conf
  template:
    src: tmux-conf.j2
    dest: ~/.tmux.conf

