---
- name: "Working around an Ansible/Aptitude issue..."
  become: true
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items:
  - aptitude
  when: (ansible_os_family == 'Debian') or (ansible_os_family == 'Parrot OS')

- name: Install all software package updates Debian
  become: true
  package:
    name: "*"
    state: "latest"
  when: ((ansible_os_family == 'Debian') or (ansible_os_family == 'Parrot OS')) and (install_all_package_updates)
  

- name: Install specified debian software package updates
  become: true
  package:
    name: "{{ item }}"
    state: latest
  with_items: "{{ update_packages }}"
  when: 
  - (ansible_os_family == 'Debian') or (ansible_os_family == 'Parrot OS')

- name: Install AUR packages
  command:  /usr/local/bin/packer -S --noconfirm --noedit {{ item }}
  with_items: "{{ update_packages }}"
  when: 
  - (ansible_os_family == 'Archlinux')

#- name: Install specified arch software package updates
#  become: true
#  yay:
#    name: "{{ item }}"
#    state: latest
#  with_items: "{{ update_packages }}"
#  when: 
#  - (ansible_os_family == 'Archlinux')

- name: Install all software package updates Arch
  become: true
  pacman:
    update_cache: yes
    upgrade: yes
  when: (ansible_os_family == 'Archlinux') and (install_all_package_updates)