---
- name: "Working around an Ansible/Aptitude issue..."
  become: true
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items:
  - aptitude
  when: (ansible_os_family == 'Debian') or (ansible_os_family == 'Parrot OS')

- name: Install all software package updates
  become: true
  package:
    name: "*"
    state: "latest"
  when: ((ansible_os_family == 'Debian') or (ansible_os_family == 'Parrot OS')) and (install_all_package_updates)
  

- name: Install specified software package updates
  become: true
  package:
    name: "{{ item }}"
    state: latest
  with_items: "{{ update_packages }}"
  when: 
  - (ansible_os_family == 'Debian') or (ansible_os_family == 'Parrot OS')
