---
- name: Install additional software packages
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ install_packages }}"
  when: 
  - ansible_facts['system'] == "Linux"

- name: Install Linux software packages
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ install_linux_packages }}"
  when: 
  - ansible_facts['system'] == "Linux"

- name: Remove specified software packages
  become: true
  package:
    name: "{{ item }}"
    state: absent
  with_items: "{{ remove_linux_packages }}"
  when: 
  - ansible_facts['system'] == "Linux"
        
    