---
- name: "Working around an Ansible/Aptitude issue..."
  become: true
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items:
  - aptitude
  when: ansible_os_family == 'Debian'

- name: Install all software package updates
  become: true
  package:
    name: "*"
    state: "latest"
  when: 
  - install_all_package_updates
  - ansible_facts['system'] == "Linux"
  

- name: Install specified software package updates
  become: true
  package:
    name: "{{ item }}"
    state: latest
  with_items: "{{ update_packages }}"
  when: 
  - ansible_facts['system'] == "Linux"
