---

- name: Ensure Docker Group is present
  become: yes
  become_user: "{{ ansible_user_id }}"
  group:
    name: docker
    state: present

- include_tasks: debian.yml
  tags: debian
  when: ansible_os_family is defined and ansible_os_family == 'Debian'

- include_tasks: macos.yml
  tags: macos
  when: ansible_facts['system'] == "Darwin"

- name: Add the user to the Docker group
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes