#!/usr/bin/env ansible-playbook
- hosts: localhost
  connection: local
  tasks:
  - debug:
      msg: Check we are running in the directory of the script
    failed_when: not ansible_env.PWD.endswith('/ansible')

- hosts: localhost
  become_method: sudo
  connection: local
  gather_facts: True
  vars:
    install_all_package_updates: true
    install_packages:
      - htop
      - glances
      - golang
      - cmake
      - tmux
      - wget
      - httpie
      - neofetch
      - graphviz
      - wget
      # - joplin - not available linux
    install_linux_packages:
      - zsh
      - powertop
      - net-tools
      - build-essential
      - module-assistant
      - timeshift
      - pydf
      - virtualbox
      - kitty
    install_mac_cask_packages:
      - virtualbox
      - kitty
      - joplin
    
  roles:
    - crossplatform-package-manager
    - role: joplinapp-linux
      users:
      - username: daco
        settings:
          - { key: "sidebarVisibility", val: "1" }
          - { key: "dateFormat", val: "YYYY-MM-DD" }
          - { key: "sync.target", val: "5" }





  #Virtualization and Cloud Automation

  #checkInstalledInstall vagrant #FIX
  #checkInstalledInstall vagrant-manager #FIX
  #checkInstalledInstall watch
  #Install Geek Terminal
