#!/usr/bin/env ansible-playbook
- hosts: localhost
  connection: local
  tasks:
    - debug:
        msg: Check we are running in the directory of the script
      failed_when: not ansible_env.PWD.endswith('/ansible')

- hosts: localhost
  strategy: free
  become_method: sudo
  connection: local
  gather_facts: True
  vars:
    install_all_package_updates: true
    repo_brew_tap:
      - homebrew/cask
      - homebrew/cask-fonts
    install_arch_linux_aur_packages:
      - vscodium-bin
      - go
      - timeshift-bin
      - stacer
      #- ttf-firacode
      - powerline-fonts
      - nerd-fonts-hack
      - azure-cli
      - vlc-luajit
    install_debian_linux_packages:
      #- codium
      - golang
      - timeshift
      - stacer
      - fonts-firacode
      - fonts-powerline
      - build-essential
      - module-assistant
      - vlc
    install_linux_packages:
      #- alacritty
      - zsh
      - powertop
      - net-tools
      - pydf
      #- virtualbox
      - flameshot #screenshot tool
      #- vagrant
    install_mac_packages:
      #- sshpass #https://raw.githubusercontent.com/kadwanev/bigboybrew/master/Library/Formula/sshpass.rb
      - watch
      - jq
      - nano
      - golang
      - azure-cli
      - derailed/k9s/k9s
      - romkatv/powerlevel10k/powerlevel10k
      #- openlens
    install_mac_cask_packages:
      #- virtualbox
      - alacritty
      #- joplin
      - font-fira-code
      - font-hack-nerd-font
      - vlc
      #- vagrant
      - vscodium
    install_packages:
      - htop
      - glances
      - cmake
      - tmux
      - wget
      - httpie
      - neofetch
      - graphviz
      - wget
      - bash-completion
      - fzf #https://github.com/junegunn/fzf
  roles:
    - kubectx
    - kubectl
    - nanorc
    - packer
    - terraform
    - awscli
    - powerline-fonts
    - crossplatform-package-manager
    #- dep
    - nerdfonts
    #- docker
    - role: oh-my-zsh
      users:
        - username: "{{ ansible_user_id | default('daco') }}"
          oh_my_zsh:
            theme: robbyrussell
            plugins:
              - git
    #- role: joplinapp-linux
    #  users:
    #  - username: "{{ ansible_user_id }}"
    #    settings:
    #      - { key: "sidebarVisibility", val: "1" }
    #      - { key: "dateFormat", val: "YYYY-MM-DD" }
    #      - { key: "sync.target", val: "5" }
    - role: tmux
      vars:
        ctrlkey: "C-"
        splitv: "\\\\"
        splith: "-"
        city: "Ermesinde"
      when:
        - ansible_facts['system'] == "Linux"
    - role: tmux
      vars:
        ctrlkey: "^"
        splitv: "\\\\"
        splith: "-"
        city: "Porto"
      when:
        - ansible_facts['system'] == "Darwin"
    - role: vscodium
      vars:
        terminal_font: "Hack"
      users:
        - username: "{{ ansible_user_id | default('daco') }}"
          #visual_studio_code_extensions:
          visual_studio_code_settings_overwrite: yes
      when:
        - ansible_facts['system'] == "Linux"
    - role: vscodium
      vars:
        terminal_font: "Hack Nerd Fonts"
      users:
        - username: "{{ ansible_user_id }}"
          #visual_studio_code_extensions:
          visual_studio_code_settings_overwrite: yes
      when:
        - ansible_facts['system'] == "Darwin"
