#!/usr/bin/env ansible-playbook
- hosts: localhost
  connection: local
  tasks:
    - debug:
        msg: Check we are running in the directory of the script
      failed_when: not ansible_env.PWD.endswith('/ansible')

- hosts: localhost
  become_method: sudo
  connection: local
  gather_facts: True
  vars:
    install_all_package_updates: true
    repo_brew_tap:
      - homebrew/cask
      - homebrew/cask-fonts
    install_linux_packages:
      - zypper
      - stacer
      - alacritty
      - timeshift # Backup Linux
      - zsh
      - powertop
      - net-tools
      - build-essential
      - module-assistant
      - pydf
      - virtualbox
      - flameshot #screenshot tool
      - fonts-firacode
      - fonts-powerline
      - vlc
      - vagrant
      - codium
    install_mac_packages:
      - homebrew/cask
      - sshpass #https://raw.githubusercontent.com/kadwanev/bigboybrew/master/Library/Formula/sshpass.rb
      - watch
      - jq
      - nano
    install_mac_cask_packages:
      - virtualbox
      - alacritty
      - joplin
      - font-fira-code
      - font-hack-nerd-font
      - vlc
      - vagrant
      - vscodium
    install_packages:
      - htop
      - glances
      - golang
      - cmake
      - tmux
      - wget
      - httpie
      - neofetch
      - graphviz
      - wget
      - bash-completion
      - fzf #https://github.com/junegunn/fzf
  roles:
    - kubectx
    - kubectl
    #- kitty
    - dep
    - nanorc
    #- packer
    - terraform
    - awscli
    - azure-cli
    - crossplatform-package-manager
    - nerdfonts
    - docker
    - role: oh-my-zsh
      users:
        - username: "{{ ansible_user_id }}"
          oh_my_zsh:
            theme: robbyrussell
            plugins:
              - git
    #- role: joplinapp-linux
    #  users:
    #  - username: "{{ ansible_user_id }}"
    #    settings:
    #      - { key: "sidebarVisibility", val: "1" }
    #      - { key: "dateFormat", val: "YYYY-MM-DD" }
    #      - { key: "sync.target", val: "5" }
    #- role: vscode
    #  users:
    #    - username: "{{ ansible_user_id }}"
    #      visual_studio_code_extensions:
    #        - streetsidesoftware.code-spell-checker
    #        - wholroyd.jinja
    #        - ms-python.python
    #        - ms-azuretools.vscode-docker
    #        - golang.Go
    #        - pkief.material-icon-theme
    #        - yzhang.markdown-all-in-one
    #      visual_studio_code_settings_overwrite: yes
    #      visual_studio_code_settings: {
    #        "workbench.colorCustomizations": {
    #          "activityBarBadge.background": "#80CBC4",
    #          "list.activeSelectionForeground": "#80CBC4",
    #          "list.inactiveSelectionForeground": "#80CBC4",
    #          "list.highlightForeground": "#80CBC4",
    #          "scrollbarSlider.activeBackground": "#80CBC450",
    #          "editorSuggestWidget.highlightForeground": "#80CBC4",
    #          "textLink.foreground": "#80CBC4",
    #          "progressBar.background": "#80CBC4",
    #          "pickerGroup.foreground": "#80CBC4",
    #          "tab.activeBorder": "#80CBC4",
    #          "terminal.background": "#050f2e",
    #          "terminal.foreground": "#839496",
    #          "terminal.ansiBlack": "#003541",
    #          "terminal.ansiBlue": "#268bd2",
    #          "terminal.ansiBrightBlack": "#586e75",
    #          "terminal.ansiBrightBlue": "#839496",
    #          "terminal.ansiBrightCyan": "#93a1a1",
    #          "terminal.ansiBrightGreen": "#586e75",
    #          "terminal.ansiBrightMagenta": "#6c6ec6",
    #          "terminal.ansiBrightRed": "#cb4b16",
    #          "terminal.ansiBrightWhite": "#fdf6e3",
    #          "terminal.ansiBrightYellow": "#657b83",
    #          "terminal.ansiCyan": "#2aa198",
    #          "terminal.ansiGreen": "#859901",
    #          "terminal.ansiMagenta": "#d33682",
    #          "terminal.ansiRed": "#dc322f",
    #          "terminal.ansiWhite": "#eee8d5",
    #          "terminal.ansiYellow": "#b58901",
    #          "terminal.selectionBackground": "#003541"
    #        },
    #        "workbench.colorTheme": "Material Theme",
    #        "terminal.integrated.fontFamily": "Hack Nerd Font",
    #        "files.autoSave": "afterDelay",
    #        "editor.formatOnSave": true,
    #        "editor.formatOnPaste": true,
    #        "editor.tabSize": 4,
    #        "editor.insertSpaces": true,
    #        "editor.renderWhitespace": "all",
    #        "terminal.integrated.fontSize": 14,
    #        "editor.fontSize": 15,
    #        "[Log]": {
    #            "editor.fontSize": 15
    #        },
    #        "window.zoomLevel": 0,
    #        "editor.fontFamily": "Fira Code",
    #        "editor.fontLigatures": true,
    #        "go.formatTool": "goimports",
    #        "go.useLanguageServer": true,
    #        "editor.rulers": [80, 100, 120],
    #        "editor.renderWhitespace": true,
    #        "files.associations": {
    #          "Vagrantfile": "ruby"
    #        }
    #      }
