#!/usr/bin/env ansible-playbook
- hosts: localhost
  connection: local
  tasks:
  - debug:
      msg: Check we are running in the directory of the script
    failed_when: not ansible_env.PWD.endswith('/ansible')

- hosts: localhost
  become_method: sudo
  connection: local
  gather_facts: True
  vars:
    install_all_package_updates: true
    repo_brew_tap: 
      - homebrew/cask-fonts
    install_packages:
      - htop
      - glances
      - golang
      - cmake
      - tmux
      - wget
      - httpie
      - neofetch
      - graphviz
      - wget
    install_linux_packages:
      - zsh
      - powertop
      - net-tools
      - build-essential
      - module-assistant
      - timeshift # Backup Linux
      - pydf
      - virtualbox
      - kitty
      - flameshot #screenshot tool
      - fonts-firacode
      - fonts-powerline
      - vlc
    install_mac_packages:
      - https://raw.githubusercontent.com/kadwanev/bigboybrew/master/Library/Formula/sshpass.rb
    install_mac_cask_packages:
      - virtualbox
      - kitty
      - joplin      
      - font-fira-code
      - font-hack-nerd-font
      - vlc
      

    
  roles:
    - crossplatform-package-manager
    - nerdfonts
    - docker
    - role: oh-my-zsh
      users:
        - username: "{{ ansible_user_id }}"
          oh_my_zsh:
            theme: robbyrussell
            plugins:
              - git
    - role: joplinapp-linux
      users:
      - username: "{{ ansible_user_id }}"
        settings:
          - { key: "sidebarVisibility", val: "1" }
          - { key: "dateFormat", val: "YYYY-MM-DD" }
          - { key: "sync.target", val: "5" }
    - role: vscode
      users:
        - username: "{{ ansible_user_id }}"
          visual_studio_code_extensions:
            - streetsidesoftware.code-spell-checker
            - wholroyd.jinja
            - ms-python.python
            - ms-azuretools.vscode-docker
            - golang.Go
            - pkief.material-icon-theme
            - yzhang.markdown-all-in-one
          visual_studio_code_settings_overwrite: yes
          visual_studio_code_settings: {
            "workbench.colorTheme": "Solarized Dark",
            "workbench.iconTheme": "material-icon-theme",
            "terminal.integrated.fontFamily": "Hack Nerd Font",
            "files.autoSave": "afterDelay",
            "editor.formatOnSave": true,
            "editor.formatOnPaste": true,
            "editor.tabSize": 4,
            "editor.insertSpaces": true,
            "editor.renderWhitespace": "all",
            "terminal.integrated.fontSize": 14,
            "editor.fontSize": 15,
            "[Log]": {
                "editor.fontSize": 15
            },
            "window.zoomLevel": 0,
            "editor.fontFamily": "Fira Code",
            "editor.fontLigatures": true,
            "go.formatTool": "goimports",
            "go.useLanguageServer": true,
            "editor.rulers": [80, 100, 120],
            "editor.renderWhitespace": true,
            "files.associations": {
              "Vagrantfile": "ruby"
            }
          }