#!/usr/bin/env ansible-playbook
- hosts: localhost
  connection: local
  tasks:
  - debug:
      msg: Check we are running in the directory of the script
    failed_when: not ansible_env.PWD.endswith('/ansible')

- hosts: localhost
  become_method: sudo
  connection: local
  gather_facts: True
  vars:
    install_all_package_updates: true
    install_packages:
      - htop
      - glances
      - golang
      - cmake
      #- virtualbox
      - tmux
      - wget
      - httpie
      - neofetch
      - graphviz
      - kitty
      # - joplin - not available linux
    install_linux_packages:
      - zsh
      - powertop
      - net-tools
      - build-essential
      - module-assistant
      - timeshift
      - pydf
    remove_linux_packages:
    
  roles:
    - crossplatform-package-manager





  #Virtualization and Cloud Automation

  #checkInstalledInstall vagrant #FIX
  #checkInstalledInstall vagrant-manager #FIX
  #checkInstalledInstall watch
  #Install Geek Terminal
