---
# The name of the directory where the config is stored for this build
visual_studio_code_config_dirname: ".vscode-oss"

# Directory under $HOME where where VS Code config is stored
visual_studio_code_config_path: "{{ (ansible_distribution == 'MacOSX') | ternary('~', '.config') }}/{{ visual_studio_code_config_dirname }}"

# The package name to install
visual_studio_code_package: "{{ (visual_studio_code_build == 'insiders') | ternary('code-insiders', 'codium') }}"

# The CLI executable
visual_studio_code_exe: "{{ (visual_studio_code_build == 'insiders') | ternary('code-insiders', 'codium') }}"
